"""empty message

Revision ID: 51b4b19e6411
Revises: d4517e5eb3f1
Create Date: 2019-02-01 07:13:35.963537

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51b4b19e6411'
down_revision = 'd4517e5eb3f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shift_details', sa.Column('coverer', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shift_details', 'coverer')
    # ### end Alembic commands ###
