"""empty message

Revision ID: d4517e5eb3f1
Revises: 
Create Date: 2019-01-28 09:14:53.947890

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4517e5eb3f1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shift_details', sa.Column('day', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shift_details', 'day')
    # ### end Alembic commands ###
